--------------------------------------------------------
--  File created - Wednesday-October-10-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUDIT_SASID_EXCEPTIONS
--------------------------------------------------------

  CREATE TABLE "STATE_EQUAL_OWNER"."AUDIT_SASID_EXCEPTIONS" 
   (	"AUDIT_ID" NUMBER(*,0), 
	"FISCAL_YEAR" VARCHAR2(8 BYTE), 
	"SASID" VARCHAR2(8 BYTE), 
	"STUD_OCT_DISTRICT" VARCHAR2(6 BYTE), 
	"STUD_OCT_SCHOOL" VARCHAR2(5 BYTE), 
	"STUDENT_LAST_NAME" VARCHAR2(60 BYTE), 
	"STUDENT_FIRST_NAME" VARCHAR2(60 BYTE), 
	"STUDENT_MIDDLE_INITIAL" VARCHAR2(1 BYTE), 
	"STUDENT_GRADE" VARCHAR2(2 BYTE), 
	"STUD_OCT_FUNDING_CODE" VARCHAR2(3 BYTE), 
	"STUD_OCT_FREE_LUNCH" VARCHAR2(2 BYTE), 
	"ATTENDANCE_CODE" VARCHAR2(3 BYTE), 
	"PARENT_DISTRICT_RESIDENCE" VARCHAR2(6 BYTE), 
	"SASID_EXCEPTION" VARCHAR2(150 BYTE), 
	"ADJUSTED_FUNDING_CODE" VARCHAR2(3 BYTE), 
	"ADJUSTED_FREE_LUNCH" VARCHAR2(2 BYTE), 
	"POST_SECONDARY" VARCHAR2(2 BYTE), 
	"PUPIL_EXCEPTION" VARCHAR2(100 BYTE), 
	"AT_RISK_EXCEPTION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;
REM INSERTING into STATE_EQUAL_OWNER.AUDIT_SASID_EXCEPTIONS
SET DEFINE OFF;
