--------------------------------------------------------
--  File created - Wednesday-October-10-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUDIT_REPAYMENT
--------------------------------------------------------

  CREATE TABLE "STATE_EQUAL_OWNER"."AUDIT_REPAYMENT" 
   (	"DISTRICT_NUMBER" VARCHAR2(4 BYTE), 
	"BEGIN_FISCAL_YEAR" VARCHAR2(4 BYTE), 
	"END_FISCAL_YEAR" VARCHAR2(4 BYTE), 
	"BEGIN_FISCAL_MONTH" VARCHAR2(15 BYTE), 
	"END_FISCAL_MONTH" VARCHAR2(15 BYTE), 
	"FREQUENCY" VARCHAR2(30 BYTE), 
	"PAYMENT_AMOUNT" NUMBER(16,6), 
	"ID" NUMBER(9,0), 
	"VERSION" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;
REM INSERTING into STATE_EQUAL_OWNER.AUDIT_REPAYMENT
SET DEFINE OFF;
Insert into STATE_EQUAL_OWNER.AUDIT_REPAYMENT (DISTRICT_NUMBER,BEGIN_FISCAL_YEAR,END_FISCAL_YEAR,BEGIN_FISCAL_MONTH,END_FISCAL_MONTH,FREQUENCY,PAYMENT_AMOUNT,ID,VERSION) values ('0880','2012','2013','July','June','Monthly',-200,4189,0);
--------------------------------------------------------
--  DDL for Index AUDIT_REPAYMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STATE_EQUAL_OWNER"."AUDIT_REPAYMENT_PK" ON "STATE_EQUAL_OWNER"."AUDIT_REPAYMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;
--------------------------------------------------------
--  DDL for Index AUDIT_REPAYMENT_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "STATE_EQUAL_OWNER"."AUDIT_REPAYMENT_UNIQUE" ON "STATE_EQUAL_OWNER"."AUDIT_REPAYMENT" ("BEGIN_FISCAL_YEAR", "END_FISCAL_YEAR", "BEGIN_FISCAL_MONTH", "END_FISCAL_MONTH", "DISTRICT_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;
--------------------------------------------------------
--  Constraints for Table AUDIT_REPAYMENT
--------------------------------------------------------

  ALTER TABLE "STATE_EQUAL_OWNER"."AUDIT_REPAYMENT" ADD CONSTRAINT "AUDIT_REPAYMENT_UNIQUE" UNIQUE ("BEGIN_FISCAL_YEAR", "END_FISCAL_YEAR", "BEGIN_FISCAL_MONTH", "END_FISCAL_MONTH", "DISTRICT_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01"  ENABLE;
  ALTER TABLE "STATE_EQUAL_OWNER"."AUDIT_REPAYMENT" ADD CONSTRAINT "AUDIT_REPAYMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01"  ENABLE;
  ALTER TABLE "STATE_EQUAL_OWNER"."AUDIT_REPAYMENT" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "STATE_EQUAL_OWNER"."AUDIT_REPAYMENT" MODIFY ("PAYMENT_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "STATE_EQUAL_OWNER"."AUDIT_REPAYMENT" MODIFY ("FREQUENCY" NOT NULL ENABLE);
  ALTER TABLE "STATE_EQUAL_OWNER"."AUDIT_REPAYMENT" MODIFY ("END_FISCAL_MONTH" NOT NULL ENABLE);
  ALTER TABLE "STATE_EQUAL_OWNER"."AUDIT_REPAYMENT" MODIFY ("BEGIN_FISCAL_MONTH" NOT NULL ENABLE);
  ALTER TABLE "STATE_EQUAL_OWNER"."AUDIT_REPAYMENT" MODIFY ("END_FISCAL_YEAR" NOT NULL ENABLE);
  ALTER TABLE "STATE_EQUAL_OWNER"."AUDIT_REPAYMENT" MODIFY ("BEGIN_FISCAL_YEAR" NOT NULL ENABLE);
  ALTER TABLE "STATE_EQUAL_OWNER"."AUDIT_REPAYMENT" MODIFY ("DISTRICT_NUMBER" NOT NULL ENABLE);
