--------------------------------------------------------
--  File created - Thursday-October-18-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STATE_EQUAL_MASTER
--------------------------------------------------------

  CREATE TABLE "STATE_EQUAL_OWNER"."STATE_EQUAL_MASTER" 
   (	"VERSION" NUMBER, 
	"ID" NUMBER, 
	"ELEMENT_NAME" VARCHAR2(100 BYTE), 
	"ELEMENT_VALUE" VARCHAR2(400 BYTE), 
	"GROUP_NAME" VARCHAR2(100 BYTE), 
	"ACTIVE" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;
--------------------------------------------------------
--  DDL for Index STATE_EQUAL_MASTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STATE_EQUAL_OWNER"."STATE_EQUAL_MASTER_PK" ON "STATE_EQUAL_OWNER"."STATE_EQUAL_MASTER" ("ELEMENT_NAME", "GROUP_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;
--------------------------------------------------------
--  Constraints for Table STATE_EQUAL_MASTER
--------------------------------------------------------

  ALTER TABLE "STATE_EQUAL_OWNER"."STATE_EQUAL_MASTER" ADD CONSTRAINT "STATE_EQUAL_MASTER_PK" PRIMARY KEY ("ELEMENT_NAME", "GROUP_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01"  ENABLE;
