--------------------------------------------------------
--  File created - Thursday-October-18-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STATE_EQUAL
--------------------------------------------------------

  CREATE TABLE "STATE_EQUAL_OWNER"."STATE_EQUAL" 
   (	"DISTRICT_NUMBER" VARCHAR2(6 BYTE), 
	"DATE_CHANGED" VARCHAR2(8 BYTE), 
	"SPECED_PK" NUMBER, 
	"FUNDED_PUPIL_COUNT" NUMBER, 
	"CAT_TRANSPORTATION" NUMBER(16,6), 
	"CAT_VOCED" NUMBER(16,6), 
	"CAT_ELPA" NUMBER(16,6), 
	"CAT_SPED_DISABILITIES" NUMBER(16,6), 
	"CAT_SPED_GIFTED_TALENTED" NUMBER(16,6), 
	"SIZE_FACTOR" NUMBER(16,6), 
	"COST_OF_LIVING_FACTOR" NUMBER(16,6), 
	"PERSONNEL_COST_FACTOR" NUMBER(16,6), 
	"FORMULA_TP_WO_AT_RISK" NUMBER(16,6), 
	"FREE_LUNCH_1_8" NUMBER(16,6), 
	"FREE_LUNCH_K_12" NUMBER(16,6), 
	"MEMBER_1_8" NUMBER(16,6), 
	"TOTAL_PROGRAM_AT_RISK" NUMBER(16,6), 
	"GRAND_TOTAL_PROGRAM" NUMBER(16,6), 
	"SOT_GROSS" NUMBER(16,6), 
	"PROPERTY_TAX" NUMBER(16,6), 
	"STATE_EQUAL" NUMBER(16,6), 
	"CERT_TOTAL_PROGRAM_MILL_LEVY" NUMBER(16,6), 
	"MONTH_ENTITLE" NUMBER(16,6), 
	"YTD_ENTITLE" NUMBER(16,6), 
	"ADJ_OTHER" NUMBER(16,6), 
	"YTD_OTHER" NUMBER(16,6), 
	"ADJ_SWAP" NUMBER(16,6), 
	"YTD_SWAP" NUMBER(16,6), 
	"ALLOW_SPEND" NUMBER(16,6), 
	"TOTAL_PROGRAM_TABOR" NUMBER(16,6), 
	"TOTAL_FUND_INCLUDING_ONLINE" NUMBER(16,6), 
	"TOTAL_MAX_FUND" NUMBER(16,6), 
	"TOTAL_ADD_FUND" NUMBER(16,6), 
	"MEMBER_K_12" NUMBER(16,6), 
	"FUNDED_AT_RISK_COUNT" NUMBER(16,6), 
	"FORMULA_PUPIL_FUND" NUMBER(16,6), 
	"TOTAL_AT_RISK_FUNDING" NUMBER(16,6), 
	"CSI_ADMIN_MONTH" NUMBER(16,6), 
	"FTE" NUMBER(16,6), 
	"MINIMUM_FORMULA_FUND" NUMBER(16,6), 
	"DISTRICT_CERT_TOTAL_ADD_FUND" NUMBER(16,6), 
	"SOT_NET" NUMBER(16,6), 
	"CHARTER_SCHOOL_FPC" NUMBER(16,6), 
	"SMALL_CENTER_PAYMENTS" NUMBER(16,6), 
	"ESL_CSAP" NUMBER(16,6), 
	"MULTI_DISTRICT_ONLINE_FTE" NUMBER(16,6), 
	"SINGLE_DISTRICT_ONLINE_FTE" NUMBER(16,6), 
	"CPP" NUMBER(16,6), 
	"CHARTER_DEBT_MONTH" NUMBER(16,6), 
	"CHARTER_DEBT_YTD" NUMBER(16,6), 
	"CSI_ADMIN_YTD" NUMBER(16,6), 
	"MONTH_PAYMENT" NUMBER(16,6), 
	"YTD_PAYMENT" NUMBER(16,6), 
	"MONTH_AUDIT_REPAY" NUMBER(16,6), 
	"CSI_TOTAL_PROGRAM_FUND" NUMBER(16,6), 
	"YTD_AUDIT_REPAY" NUMBER(16,6), 
	"NEG_FACTOR" NUMBER(16,6), 
	"FISCAL_YEAR" VARCHAR2(8 BYTE), 
	"ASSESSED_VAL" NUMBER(16,6), 
	"CALC_TOTAL_PROGRAM_MILL_LEVY" NUMBER(16,6), 
	"STATE_EQUAL_ADJUST" NUMBER(16,6), 
	"STATE_AVERAGE_AT_RISK_PERCENT" NUMBER(16,6), 
	"MINIMUM_STATE_AID" NUMBER(16,6), 
	"BASE_PER_PUPIL_FUND" NUMBER(16,6), 
	"ONLINE_PER_PUPIL_FUND" NUMBER(16,6), 
	"NEG_FACTOR_ONLINE_PPF" NUMBER(16,6), 
	"AT_RISK_BASE_FACTOR" NUMBER(16,6), 
	"TOTAL_ONLINE_AND_ASCENT_FUND" NUMBER(16,6), 
	"ADJ_DISTRICT_TOTAL_PROGRAM" NUMBER(16,6), 
	"FULL_FUNDING_MILL" NUMBER(16,6), 
	"TABOR_MILL" NUMBER(16,6), 
	"SOT_ADJ_PERCENT" NUMBER(16,6), 
	"DISTRICT_CHARTER_FTE_COUNT" NUMBER(16,6), 
	"CALC_CAT_BUY_MILL_LEVY" NUMBER(16,6), 
	"CERT_CAT_BUY_MILL_LEVY" NUMBER(16,6), 
	"TOTAL_PROGRAM_CAT_BUYOUT" NUMBER(16,6), 
	"ADJ_OODS" NUMBER(16,6), 
	"CAT_LEVY_ADJ" NUMBER(16,6), 
	"MILL_LEVY_ADJ" NUMBER(16,6), 
	"YTD_OODS" NUMBER(16,6), 
	"PER_PUPIL_OPERATING_REVENUE" NUMBER(16,6), 
	"ID" NUMBER(19,0), 
	"VERSION" NUMBER(10,0) DEFAULT 0, 
	"UPDATE_TIMESTAMP" DATE DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;
--------------------------------------------------------
--  DDL for Index STATE_EQUAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STATE_EQUAL_OWNER"."STATE_EQUAL_PK" ON "STATE_EQUAL_OWNER"."STATE_EQUAL" ("FISCAL_YEAR", "DISTRICT_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;
--------------------------------------------------------
--  Constraints for Table STATE_EQUAL
--------------------------------------------------------

  ALTER TABLE "STATE_EQUAL_OWNER"."STATE_EQUAL" MODIFY ("UPDATE_TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "STATE_EQUAL_OWNER"."STATE_EQUAL" ADD CONSTRAINT "STATE_EQUAL_PK" PRIMARY KEY ("FISCAL_YEAR", "DISTRICT_NUMBER") DISABLE;
--------------------------------------------------------
--  DDL for Trigger SE_INSERT_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "STATE_EQUAL_OWNER"."SE_INSERT_ID_TRIGGER" 
BEFORE INSERT
ON STATE_EQUAL_OWNER.STATE_EQUAL
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE

BEGIN
      IF( :New.id is null )
   THEN
       :New.id := hibernate_sequence.nextval;
   END IF;

END SE_INSERT_ID_TRIGGER;
/
ALTER TRIGGER "STATE_EQUAL_OWNER"."SE_INSERT_ID_TRIGGER" ENABLE;
