--------------------------------------------------------
--  File created - Thursday-October-18-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRANSPORTATION
--------------------------------------------------------

  CREATE TABLE "STATE_EQUAL_OWNER"."TRANSPORTATION" 
   (	"DISTRICT_NUMBER" VARCHAR2(6 BYTE), 
	"DATE_CHANGED" VARCHAR2(28 BYTE), 
	"ERRORS" VARCHAR2(12 BYTE), 
	"PUPIL_TRAN" NUMBER, 
	"OPER_TRAN" NUMBER, 
	"IND_CONT" NUMBER, 
	"CAP_OUT_TRAN" NUMBER, 
	"MIG_MILES" NUMBER, 
	"REG_D_MILES" NUMBER, 
	"SCHOOL_DAYS" NUMBER, 
	"REG_DAYS" NUMBER, 
	"BOARD_TRAN" NUMBER, 
	"EX_REIM" NUMBER, 
	"DESEG_REIM" NUMBER, 
	"REIM_TRAN" NUMBER, 
	"REIM_TRAN_LY" NUMBER, 
	"ADV_PAY_LY" NUMBER, 
	"REIM_ADV_PAY" NUMBER, 
	"ADV_PAY" NUMBER, 
	"ACT_MILES" NUMBER, 
	"TOTAL_MILES" NUMBER, 
	"FISCAL_YEAR" VARCHAR2(8 BYTE), 
	"CDE_COMMENTS" VARCHAR2(4000 BYTE), 
	"FIRST_PAYMENT" NUMBER, 
	"SECOND_PAYMENT" NUMBER, 
	"DISTRICT_DISTRIBUTION" NUMBER, 
	"COFRS_BATCH_NUMBER" NUMBER, 
	"COFRS_DATE_PAID" DATE, 
	"NAME_PREPARER_CDE40" VARCHAR2(100 BYTE), 
	"PHONE_PREPARER_CDE40" VARCHAR2(15 BYTE), 
	"EMAIL_PREPARER_CDE40" VARCHAR2(100 BYTE), 
	"FEES_COLLECTED" NUMBER, 
	"OTHER_REVENUE" NUMBER, 
	"NET_CURRENT_OPER_EXPEND" NUMBER, 
	"TOTAL_REIM_MILEAGE" NUMBER, 
	"MILEAGE_ENTITLEMENT" NUMBER, 
	"EX_COSTS" NUMBER, 
	"MAX_REIM_ENTITLEMENT" NUMBER, 
	"REIM_ENTITLEMENT" NUMBER, 
	"TOTAL_REIM_ENTITLEMENT" NUMBER, 
	"FINAL_REIM_ENTITLEMENT" NUMBER, 
	"FINAL_REIM_PRORATED" NUMBER, 
	"ID" NUMBER(19,0), 
	"VERSION" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;
--------------------------------------------------------
--  DDL for Index TRANSPORTATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STATE_EQUAL_OWNER"."TRANSPORTATION_PK" ON "STATE_EQUAL_OWNER"."TRANSPORTATION" ("DISTRICT_NUMBER", "FISCAL_YEAR", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;
--------------------------------------------------------
--  Constraints for Table TRANSPORTATION
--------------------------------------------------------

  ALTER TABLE "STATE_EQUAL_OWNER"."TRANSPORTATION" ADD CONSTRAINT "TRANSPORTATION_PK" PRIMARY KEY ("DISTRICT_NUMBER", "FISCAL_YEAR", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01"  ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRANS_INSERT_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "STATE_EQUAL_OWNER"."TRANS_INSERT_ID_TRIGGER" 
BEFORE INSERT
ON STATE_EQUAL_OWNER.TRANSPORTATION
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE

BEGIN
      IF( :New.id is null )
   THEN
       :New.id := hibernate_sequence.nextval;
   END IF;

END TRANS_INSERT_ID_TRIGGER;
/
ALTER TRIGGER "STATE_EQUAL_OWNER"."TRANS_INSERT_ID_TRIGGER" ENABLE;
